name: CD
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: dotnet-version: 8.0.x
      - name: Publish API
        run: dotnet publish DocVault.Api/DocVault.Api.csproj -c Release -o ./publish
      - name: Deploy API to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: docvault-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
      - name: Build Angular
        run: |
          cd docvault-ui
          npm install
          npm run build
      - name: Deploy Angular
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "docvault-ui/dist"
          output_location: "/"
